# event-bus-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
  labels:
    app: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus
        image: tauseefrazaq/event-bus:latest
        ports:
        - containerPort: 3236
        # Add your environment variables here
        # env:
        # - name: ENV_VAR_NAME
        #   value: "ENV_VAR_VALUE"
---
# event-bus-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
spec:
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 3238
      targetPort: 3238