# post-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: tauseefrazaq/post:latest
        ports:
        - containerPort: 3236
        # Add your environment variables here
        # env:
        # - name: ENV_VAR_NAME
        #   value: "ENV_VAR_VALUE"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
---
# post-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 3239
      targetPort: 3239