# auth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classrooms-deployment
  labels:
    app: classrooms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classrooms
  template:
    metadata:
      labels:
        app: classrooms
    spec:
      containers:
      - name: classrooms
        image: tauseefrazaq/classrooms:latest
        ports:
        - containerPort: 3236
        # Add your environment variables here
        # env:
        # - name: ENV_VAR_NAME
        #   value: "ENV_VAR_VALUE"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
---
# classrooms-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: classrooms-service
spec:
  selector:
    app: classrooms
  ports:
    - protocol: TCP
      port: 3237
      targetPort: 3237